import Head from 'next/head'
import Image from 'next/image'

interface Props {
  banners?:Array<string>
}

const Home: React.FC<Props> = () => {
  return (
    <div className="">
      <Head>
        <title>{"Next Typescript Tailwind Boilerplate"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:title" content="Next Typescript Tailwind Boilerplate" />
        <meta property="og:type" content="video.movie" />
        <meta property="og:url" content="https://www.imdb.com/title/tt0117500/" />
        <meta property="og:image" content="/webmindsters_ograph.webp" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        
      </main>

      <footer></footer>
    </div>
  )
}

export default Home;
